name: ⚙️ Validate
run-name: "Validate: ${{ github.sha }}${{ (!inputs.infra && !inputs.app) && '👀 validate nothing' || ''}}${{ inputs.infra && ' ✓  infra' || '' }}${{ inputs.app && ' ✓  app' || '' }}"
on:
  workflow_dispatch:
    inputs:
      check-infra:
        description: "Validate Infra"
        default: true
        required: true
        type: boolean
      check-app:
        description: "Validate App"
        default: true
        required: true
        type: boolean

permissions:
  contents: read
  id-token: write

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/sub-ci.yml
    secrets: inherit
    with:
      check-infra: ${{ inputs.check-infra }}
      check-app: ${{ inputs.check-app }}
